const EXCEPTION_KEYS = {
    UN_ALLOWED_LOGIN_EMAIL: 'UN_ALLOWED_LOGIN_EMAIL',
    LIMIT_ACTIVE_GIFT_PERIOD: 'LIMIT_ACTIVE_GIFT_PERIOD',
    INVALID_GIFT_PERIOD_ENDTIME: 'INVALID_GIFT_PERIOD_ENDTIME',
    REQUIRE_GIFT: 'REQUIRE_GIFT',
    GIFT_PERIOD_INTERSECTION_TIME: 'GIFT_PERIOD_INTERSECTION_TIME',
    EXCHANGE_REQUEST_INVALID_POINT: 'EXCHANGE_REQUEST_INVALID_POINT',
    EXCHANGE_REQUEST_INVALID_QUANTITY: 'EXCHANGE_REQUEST_INVALID_QUANTITY',
    ABSENCE_CONFLICT_REQUEST: 'ABSENCE_CONFLICT_REQUEST',

    KUDOS_SELF_GIVE: 'KUDOS_SELF_GIVE',
    KUDOS_LIMIT_KUDOS_PER_MONTH: 'KUDOS_LIMIT_KUDOS_PER_MONTH',
    KUDOS_DUPLICATED_GIVE: 'KUDOS_DUPLICATED_GIVE',
};

export default EXCEPTION_KEYS;
