name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Deploy to Azure VM
        env:
          HOST: ${{ secrets.HOST }}  # Replace with your Azure VM's IP
          USER: ${{ secrets.USERNAME }}     # Replace with your SSH username
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            # Navigate to the project directory
            cd /sources/led_controller_be
  
            # Pull the latest changes
            git pull origin main
  
            # Install dependencies (example for a Node.js project)
            npm install
  
            # Restart the application (example for a PM2 managed Node.js app)      
            pm2 restart thesis-api
          EOF
