# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - api-led-controller

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AZURE_VM_SSH_KEY }}

      - name: Deploy to Azure VM
        env:
          HOST: '20.2.116.72'  # Replace with your Azure VM's IP
          USER: 'xuanloc'     # Replace with your SSH username
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            # Navigate to the project directory
            cd /sources/backend
  
            # Pull the latest changes
            git pull origin main
  
            # Install dependencies (example for a Node.js project)
            npm install
  
            # Restart the application (example for a PM2 managed Node.js app)
            pm2 restart your-app-name
  
            # Any other deployment commands
          EOF
          
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'api-led-controller'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C4BFB5C5FD0C47C0A74CAE8B3D108166 }}
