name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Azure VM
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'

            # Navigate to the project directory
            cd /var/www/led_controller_be
            
            echo "Kill all the running PM2 actions"
            pm2 kill
            
            # Pull the latest changes
            echo "Update app from Git"
            git checkout main  && git pull origin main

            # Install dependencies (example for a Node.js project)
            npm install

            echo "Build code"
            npm run build

            echo "Who I am"
            whoami

            pm2 list

            echo "Restart the application"      
            pm2 start dist/main.js --name main-service
          EOF
